const C=window.SUPABASE_CONFIG||{};const db=C.url&&!C.url.includes('YOUR_')?supabase.createClient(C.url,C.anonKey):null;let tab='pending';let user=null;
const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(m,bad=false){const d=document.createElement('div');d.textContent=m;d.style='position:fixed;right:18px;bottom:18px;background:'+(bad?'#991b1b':'#1c1715')+';color:#fff;padding:12px 16px;border-radius:9px;font-size:12px;z-index:99';$('toast').appendChild(d);setTimeout(()=>d.remove(),3000)}
function fmt(x){return x?new Date(x+'T00:00:00').toLocaleDateString(undefined,{day:'numeric',month:'short',year:'numeric'}):'—'}
async function profile(){let {data,error}=await db.from('profiles').select('*').eq('id',user.id).single();if(error||data?.role!=='admin'){await db.auth.signOut();user=null;$('dashboard').classList.add('hidden');$('loginPanel').classList.remove('hidden');toast('This account is not an administrator.',true);return false} $('adminName').textContent=data.full_name;return true}
async function login(e){e.preventDefault();if(!db){toast('Add Supabase credentials to config.js.',true);return}let {data,error}=await db.auth.signInWithPassword({email:$('email').value,password:$('password').value});if(error){toast(error.message,true);return}user=data.user;if(await profile()){ $('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');await load()}}
async function load(){let [d,r,p]=await Promise.all([db.from('profiles').select('*',{count:'exact',head:true}).eq('role','donor'),db.from('blood_requests').select('*',{count:'exact',head:true}),db.from('request_responses').select('*',{count:'exact',head:true})]);let pend=await db.from('blood_requests').select('*',{count:'exact',head:true}).eq('status','pending');$('stats').innerHTML=`<div class="stat"><b>${d.count||0}</b><span>Registered donors</span></div><div class="stat"><b>${r.count||0}</b><span>Total requests</span></div><div class="stat"><b>${pend.count||0}</b><span>Pending verification</span></div><div class="stat"><b>${p.count||0}</b><span>Donor responses</span></div>`;render()}
async function render(){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===tab));let box=$('content');if(tab==='pending'||tab==='requests'){let q=db.from('blood_requests').select('*').order('created_at',{ascending:false}).limit(300);if(tab==='pending')q=q.eq('status','pending');let {data,error}=await q;if(error){toast(error.message,true);return}box.innerHTML=data?.length?`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Patient</th><th>Group</th><th>Hospital</th><th>Location</th><th>Date</th><th>Priority</th><th>Status</th><th>Action</th></tr></thead><tbody>${data.map(r=>`<tr><td>${esc(r.patient_name)}</td><td><b>${r.blood_group}</b></td><td>${esc(r.hospital)}</td><td>${esc(r.location)}</td><td>${fmt(r.required_date)}</td><td>${r.priority}</td><td>${r.status}</td><td>${r.status==='pending'?`<button class="mini ok" onclick="setReq('${r.id}','verified')">Verify</button> <button class="mini no" onclick="setReq('${r.id}','rejected')">Reject</button>`:r.status==='verified'?`<button class="mini no" onclick="setReq('${r.id}','cancelled')">Cancel</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p style="color:#777">No requests found.</p>'}
else if(tab==='donors'){let {data,error}=await db.from('profiles').select('*').eq('role','donor').order('created_at',{ascending:false}).limit(300);if(error){toast(error.message,true);return}box.innerHTML=`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Name</th><th>Group</th><th>Location</th><th>Phone</th><th>Available</th><th>Joined</th></tr></thead><tbody>${(data||[]).map(d=>`<tr><td>${esc(d.full_name)}</td><td>${d.blood_group}</td><td>${esc(d.location)}</td><td>${esc(d.phone||'—')}</td><td>${d.is_available?'Yes':'No'}</td><td>${new Date(d.created_at).toLocaleDateString()}</td></tr>`).join('')}</tbody></table></div>`}
else{let {data,error}=await db.from('request_responses').select('id,status,created_at,profiles:donor_id(full_name,blood_group),blood_requests:request_id(patient_name,hospital,blood_group)').order('created_at',{ascending:false}).limit(300);if(error){toast(error.message,true);return}box.innerHTML=`<div class="table-wrap"><table class="admin-table"><thead><tr><th>Donor</th><th>Group</th><th>Patient</th><th>Hospital</th><th>Status</th></tr></thead><tbody>${(data||[]).map(x=>`<tr><td>${esc(x.profiles?.full_name)}</td><td>${x.profiles?.blood_group||'—'}</td><td>${esc(x.blood_requests?.patient_name)}</td><td>${esc(x.blood_requests?.hospital)}</td><td>${x.status}</td></tr>`).join('')}</tbody></table></div>`}}
async function setReq(id,status){let {error}=await db.from('blood_requests').update({status}).eq('id',id);if(error){toast(error.message,true);return}toast('Request updated.');await load()}
$('loginForm').onsubmit=login;$('refresh').onclick=()=>load();$('logout').onclick=async()=>{await db.auth.signOut();location.reload()};document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>{tab=x.dataset.tab;render()});
(async()=>{if(!db)return;let {data}=await db.auth.getSession();if(data.session){user=data.session.user;if(await profile()){$('loginPanel').classList.add('hidden');$('dashboard').classList.remove('hidden');load()}}})();
